import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import Styles from "../styles/Catogries.module.scss"
import { BsFillEnvelopeOpenFill,BsPeopleFill } from 'react-icons/bs'
import Link from 'next/link'
export default function Catogries() {
    return (
        <>
            <Head>
                <title>Milson</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/img/logo.jpg" />
            </Head>
            <div className={Styles.Catogries}>
                <nav className='d-flex align-items-center justify-content-end'>
                    <Image alt='logo' className='mt-3 m-auto mx-md-5' src='/img/logo.jpg' width='140' height='100' />
                </nav>
                <h2 className='mt-3 text-center'>Open a free account</h2>
                <p className='mt-3 d-block text-center'>Start localizing today.</p>
                <div className={Styles.ChooseCatogry}>
                    <div className={`col-md-5 col-11 ${Styles.box} ${Styles.firstbox}`}>
                    <Link href='/RegisterEnglish'>
                        <a>
                          <div className='d-flex align-items-center justify-content-center ps-3'>
                                <BsFillEnvelopeOpenFill />
                                <div className='ps-4'>
                            <h5>Join to English Department</h5>
                           <p>Start a localization project with just a click</p>
                                </div>
                          </div>
                        </a>
                    </Link>
                    </div>
                    <div className={`col-md-5 col-11 ${Styles.box} ${Styles.secondbox}`}>
                    <Link href='/RegisterTranslation'>
                        <a>
                          <div className='d-flex align-items-center justify-content-center ps-3'>
                                <BsPeopleFill />
                                <div className='ps-4'>
                            <h5>Join to Translation Department</h5>
                           <p>Start a localization project with just a click</p>
                                </div>
                          </div>
                        </a>
                    </Link>
                    </div>
                </div>
              
            </div>
        </>

    )
}
