import React, { useState } from 'react'
import Head from 'next/head'
import NavbarHome from '../components/NavbarHome.jsx'
import Header from '../components/Header.jsx'
export default function Home({ popular }) {
  return (
    <div>
      <Head>
        <title>Milson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.jpg" />
      </Head>
      <>
        <NavbarHome />
        <Header />
      </>
    </div>
  )
}