import React from 'react'
import SignUp from '../components/SignUp'
import Head from 'next/head'
export default function RegisterTranslation() {
  return (
    <>
      <Head>
        <title>Milson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.jpg" />
      </Head>
    <div>
        <SignUp prop={"Join as a Translator"} Url={"Translation"}/>
    </div>
    </>
  )
}
